#
# Copyright 2025  by Bastien Baranoff
#
services:
  example:
    build:
        context: .
        args:
            DOCKER_BUILDKIT: 1
            LIMESDR: ${CONFIG_HARDWARE_LIMESDR} # here it is!
